# Generated by Django 6.0.2 on 2026-02-24 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_remove_cafeteriamenu_is_preorder_available_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='busroute',
            options={'verbose_name_plural': 'Bus Routes'},
        ),
        migrations.AlterModelOptions(
            name='cafeteriamenu',
            options={'ordering': ['day', 'meal_type'], 'verbose_name_plural': 'Cafeteria Menus'},
        ),
        migrations.AlterModelOptions(
            name='faculty',
            options={'verbose_name_plural': 'Faculties'},
        ),
        migrations.RenameField(
            model_name='course',
            old_name='course_name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='busschedule',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='course',
            name='code',
            field=models.CharField(default='TEMP', max_length=10, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cafeteriamenu',
            name='meal_type',
            field=models.CharField(choices=[('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner'), ('Snacks', 'Snacks')], max_length=20),
        ),
        migrations.AlterField(
            model_name='classschedule',
            name='day_of_week',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=15),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
