# Generated by Django 5.1.7 on 2025-03-20 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_remove_cafeteriamenu_is_preorder_available_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='bus_schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('student', 'Student'), ('staff', 'Staff'), ('faculty', 'Faculty'), ('admin', 'Admin')], default='student', max_length=10)),
                ('id_number', models.CharField(max_length=20, unique=True)),
                ('level', models.CharField(blank=True, max_length=50, null=True)),
                ('term', models.CharField(blank=True, max_length=50, null=True)),
                ('contact_information', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='mealbooking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.user'),
        ),
    ]
