# Generated by Django 5.1.6 on 2026-03-03 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0006_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="profile_image",
            field=models.ImageField(blank=True, null=True, upload_to="profile_images/"),
        ),
    ]
