# Generated by Django 5.1.6 on 2026-03-04 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0007_profile_profile_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="blood_group",
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name="profile",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
    ]
